### PR TITLE
Added a docs folder, and a GIF demoing Scrybe in README

### PR DESCRIPTION
**Pull request by sim-s-singh**
I added a docs folder for any future documentation that is too complex for the README.
I also made a GIF that demos Scrybe and added that to the docs folder.
I then added that GIF to the README.
This solves the issue that a lot on Reddit have about there being nothing actually demonstrating the program.

### CODE REVIEW

**Comment by oliverb123** [comment]
I'd pull this, and I really appreciate the effort, but in the gif when you type `a;new-note;[tag1, tag2]`, you've actually created a note with the tags `["[tag1", "tag2]"]`. The square brackets in the doc are markup to show that tags are optional for the note creation command. Do you think there's a way I could make that more clear? It makes sense to me, but I wrote the code so I don't have an outsiders eyes here, I'd appreciate any suggestions.

**Comment by sim-s-singh** [comment]
Would it be better if I made a new GIF, and removed the [tab1,tag2] thing?

**Comment by sim-s-singh** [comment]
As for the tags, I think you should make the program say that non-alphanumeric characters aren't accepted in tags, and that the user has to recreate the note.
I will make the GIF as soon as I can, but I am currently busy.
As for you, sleep might be something yah need.

**Comment by oliverb123** [comment]
You ain't wrong, but if I could I would. I think warning on non-alphanumerics is better than an outright ban on them, I'm gonna go with that for now. Make the gif whenever you get the chance, there'll probably be a new commit by then tho

**Pull request closed without merging**
